version: "3.9"

services:
   hydro_api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      container_name: Hydro_API
      command: python3 manage.py runserver 0.0.0.0:8000
      #volumes here mounts the code to the container and updates
      #changes are made to source code
      volumes:
         - .:/app
      ports:
          - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - hydro_api

   postgres-db:
      image: kartoza/postgis:12.0
      ports:
         - 5433:5432
      volumes:
         #for persistent storage
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DB=${POSTGRES_DB}
      restart: "on-failure"
      networks:
         - hydro_api

networks:
   hydro_api:
      driver: bridge

volumes:
   postgres_data: