# Generated by Django 3.1.5 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoklanskyHajenka',
            fields=[
                ('wl_mm', models.FloatField(blank=True, db_column='WL_mm', null=True)),
                ('ec_lin_micros_cm', models.FloatField(blank=True, db_column='EC_lin_microS/cm', null=True)),
                ('ec_nonlin_micros_cm', models.FloatField(blank=True, db_column='EC_nonlin_microS/cm', null=True)),
                ('ec_uncomp_micros_cm', models.FloatField(blank=True, db_column='EC_uncomp_microS/cm', null=True)),
                ('wt_degc', models.FloatField(blank=True, db_column='WT_degC', null=True)),
                ('date_time', models.DateTimeField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'roklansky_hajenka',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='ptaipotokisco',
            table='ptaci_potok_isco',
        ),
    ]
