# Generated by Django 3.1.5 on 2024-06-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0002_auto_20240602_1757'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ptaipotokisco',
            table='ptaсi_potok_isco',
        ),
    ]
