# Generated by Django 3.1.5 on 2024-06-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydro', '0003_auto_20240607_1118'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ptaipotokisco',
            table='ptaci_potok_isco',
        ),
    ]
